yadm add ~/.config/btop/
yadm add ~/.config/cava/
yadm add ~/.config/corectrl/
yadm add ~/.config/dunst/
yadm add ~/.config/fastfetch/
yadm add ~/.config/fish/
yadm add ~/.config/foot/
yadm add ~/.config/goverlay/
yadm add ~/.config/htop/
yadm add ~/.config/hypr/
yadm add ~/.config/input-remapper-2/
yadm add ~/.config/kitty/
yadm add ~/.config/Kvantum/
yadm add ~/.config/lazygit/
yadm add ~/.config/MangoHud/
yadm add ~/.config/micro/
yadm add ~/.config/mpv/
yadm add ~/.config/nvim/
yadm add ~/.config/OpenRGB/
yadm add ~/.config/rofi/
yadm add ~/.config/swappy/
yadm add ~/.config/swaylock/
yadm add ~/.config/swaync/
yadm add ~/.config/tabliss/
yadm add ~/.config/Thunar/
yadm add ~/.config/wal/
yadm add ~/.config/waybar/
yadm add ~/.config/kdeglobals
yadm add ~/.config/starship.toml
yadm add ~/.config/scripts/
yadm add ~/.config/matugen/
yadm add ~/.config/qt5ct/
yadm add ~/.config/qt6ct/
yadm add ~/.config/ags/
yadm add ~/.config/gtk-2.0/
yadm add ~/.config/gtk-3.0/
yadm add ~/.config/gtk-4.0/
yadm add ~/.config/zathura/
yadm add ~/.config/menus/
yadm add ~/.config/wallust/
yadm add ~/.config/waypaper/
yadm add ~/Pictures/wallpapers/
yadm add ~/Pictures/wallpapers_live/
yadm add ~/.local/bin/scripts/
yadm add ~/.config/catppuccin_themes/
yadm add ~/yadm_add.sh
yadm add ~/.config/xdg-desktop-portal/
yadm add ~/misc/
yadm add ~/.config/gotop/
yadm add ~/.config/hellwal/
yadm add ~/.config/kew/kewrc
