general {
    grab_focus = true
}

cache {
    enabled = true
}

finders {
    # App launcher by default
    default_finder = desktop

    # Prefixes
    unicode_prefix = .
    math_prefix = =
    font_prefix = '

    # Keep desktop clean
    desktop_icons = true

    # For uwsm users only.
    # Remove if not using uwsm
    # desktop_launch_prefix = "uwsm app -- "
}

ui {
    # Tuned for 3440x1440 ultrawide
    window_size = 920 620
}