# ==========================
# Hyprtoolkit Theme
# Catppuccin Mocha + custom accent
# ==========================

# Main backgrounds
background = 0xFF11111B      # Crust
base = 0xFF1E1E2E            # Base
alternate_base = 0xFF313244  # Surface0

# Text
text = 0xFFCDD6F4            # Text
bright_text = 0xFFFFFFFF

# Accent
accent = 0xFFBA98E3
accent_secondary = 0xFF89B4FA

# Typography
font_size = 13
small_font_size = 11

h1_size = 24
h2_size = 19
h3_size = 16

# Replace if you use another font
font_family = "JetBrainsMono Nerd Font"
font_family_monospace = "JetBrainsMono Nerd Font"

# Icons
icon_theme = "BeautyLine_pywal"

# Rounding
rounding_large = 18
rounding_small = 10