theme {
    color_scheme = /home/itachi/.local/share/color-schemes/CatppuccinMochaColorAdapt.colors
    icon_theme = BeautyLine_pywal
    style = kvantum-dark
    font_fixed = JetBrains Mono NL SemiBold
    font_fixed_size = 10
    font = Sans Open Sans SemiBold
    font_size = 10
}

misc {
    shortcuts_for_context_menus = true
    menus_have_icons = true
    
}