[pyprland]

plugins = ["scratchpads"]

[scratchpads.term_scratchpad]
animation = "fromTop"
# command = "kitty --class kitty-dropterm"
command = "foot --app-id foot-dropterm -e zellij attach --create scratchpad"
class = "foot-dropterm"
size = "50% 60%"
margin = 50
pinned = true

[scratchpads.kew_player]
animation = "fromTop"
command = "foot --app-id foot-kew -e kew"
class = "foot-kew"
position = "82% 4%"
size = "17% 50%"
margin = 50
pinned = true

# [scratchpads.volume]
# animation = "fromRight"
# command = "pavucontrol"
# class = "org.pulseaudio.pavucontrol"
# size = "40% 90%"
# unfocus = "hide"
# lazy = true