[display]
horizontal_padding = 3
vertical_padding = 1
width = 50
show_translation = "romaji"
translation_color = "dim"
font_size = "medium"
bold = true
border = true
rounded_border = true
source = true
modes = ["proverb", "anime"]
seed = 0
centered = true
